### ISSUE TITLE
Polari Bug: Unreadable Text

### ISSUE THREAD

**Issue by tristan957** [tista500/Adapta#107]
**Reporter info**

 ```
 * Distribution - Antergos
 * Gtk+ 3.0 version - 3.20.6
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)** - 3.21.1.225-1

**Related Application and/or Shell theming (or name of widget)** - Polari

**Actual issue** - Active IRC chat is almost unreadable with Adapta light theme as seen here: http://i.imgur.com/15wljAa.png

**Steps to reproduce (if you knew)** - Enter an IRC chat

**Expected behaviour** - Readable text

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment]
@tristan957,

Stop using external link to put images. I never trust that hosting service, so use github instead.

Regards.

**Comment by tristan957** [comment]
K. just trying to help. 
![screenshot from 2016-05-23 19-46-56](https://cloud.githubusercontent.com/assets/11936772/15490864/1e0b4246-2131-11e6-82d7-7ba866854c68.png)

Never used GitHub so I'm trying to assist you in any way I can....

**Comment by tista500** [comment]
1st trial fix was committed: https://github.com/tista500/Adapta/commit/52210bab8a14539b64fbe5f214b3e8c39e442a09

But anyway I could not reproduce in my Polari 3.20.0.

Regards.

**Comment by tista500** [comment]
Any changes?

If this issue still was remained, please re-open.

Regards.

**Comment by bil-elmoussaoui** [comment]
I still have this issue
![capture du 2016-05-27 22-55-08](https://cloud.githubusercontent.com/assets/7660997/15620982/13a55802-245e-11e6-86bc-8f5394d7fedd.png)
As you can see, the text (gnome-builder) on the sidebar is white

**Comment by tista500** [comment]
Polari 3.20.2 has changed some constructions. Now I've confirmed and fixed: https://github.com/tista500/Adapta/commit/e4aba796f87ee12eeb3bf412175485247023125f

Looks ugly... :(

Regards.

**Comment by bil-elmoussaoui** [comment]
Thanks for the fix! looks better
