### ISSUE TITLE
Black line on the top of screen

### ISSUE THREAD

**Issue by TheAifam5** [tista500/Adapta#175]
**Reporter info**

 ```
 * Distribution - ArchLinux
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Budgie Desktop
 ```

**Adapta version (if you knew)**
Git version

**Related Application and/or Shell theming (or name of widget)**
Top bar of Budgie desktop

**Actual issue**
Black line on the top of screen

**Steps to reproduce (if you knew)**
Just set the theme (Adapta-Nokto), make a screenshot and check.

**Other Note (feature-request, question, etc...)**
Standard gnome theme doesn't have that.
Example screenshot:
![top-gap](https://cloud.githubusercontent.com/assets/2192274/17095601/a3e070ee-5255-11e6-8a79-076a4801c0be.png)
Related issue: https://github.com/solus-project/budgie-desktop/issues/511

**Comment by tista500** [comment]
Fix was committed: https://github.com/tista500/Adapta/commit/ae690b2ac82e459bee5f894111fbda49a0df8d1f

Regards.

**Comment by ikeydoherty** [comment]
Ah yeah I remember the styling now in Budgie 8.x with the Chromeish window indicator in the black 2px region.. ^^ Thanks for fixing @tista500

**Comment by TheAifam5** [comment]
Still the same issue.

![issue](https://cloud.githubusercontent.com/assets/2192274/17104078/919ab094-5281-11e6-932b-c1e55a259484.png)
