### ISSUE TITLE
Checkboxes and radio buttons too big

### ISSUE THREAD

**Issue by gregorydk** [tista500/Adapta#61]
The 20px checkboxes and radio buttons are too big. They mess up layouts on websites and in CMS's.

**Comment by tista500** [comment]
@gregorydk.

Your issue messed me.
Without explanations about platform, version, apps, and there's few things I should read...

Invalid.

**Comment by gregorydk** [comment]
![adapta-checkboxes_2016-04-24](https://cloud.githubusercontent.com/assets/7804464/14766245/861f7910-0a02-11e6-91da-94ae789c896a.png)

Checkboxes should be aligned to the right.

**Comment by tista500** [comment]
Why you did NOT explain your environment? :(

Anyway issue was solved.

**Comment by gregorydk** [comment]
Not quite solved yet. Bug is still present in GNOME 3.20. You forgot to also change it in gtk-3.0.

**Comment by tista500** [comment]
Use other theme.

That's all.

**Comment by gregorydk** [comment]
My mistake. Ignore my last message, theme didn't reload properly. It is OK now.
